Undo test changes

diff --git a/.github/workflows/build_publish.yml b/.github/workflows/build_publish.yml
--- a/.github/workflows/build_publish.yml
+++ b/.github/workflows/build_publish.yml
@@ -2,7 +2,7 @@ name: Build and Publish
 on:
   push:
     branches:
-      - feature/ipd-microfrontend
+      - Bahmni-IPD-master
     paths-ignore:
       - "**.md"
 
@@ -53,23 +53,23 @@ jobs:
           platforms: linux/amd64,linux/arm64
           file: package/docker/Dockerfile
           push: true
-          tags: bahmni/bahmni-web:ipd-wip
-  # trigger-workflow:
-  #   name: Trigger workflow to deploy to Docker env
-  #   needs:
-  #     - build-publish-docker
-  #     - Trivy
-  #   runs-on: ubuntu-latest
-  #   env:
-  #     EVENT_TYPE: openmrs-module-bahmniapps-event
-  #   steps:
-  #     - name: Create repository_dispatch
-  #       run: |
-  #         trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.IPD_PAT }}' https://api.github.com/repos/${{ secrets.IPD_ORG_NAME }}/${{ secrets.IPD_REPOSITORY_NAME }}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
-  #         if [ $trigger_result == 204 ];then
-  #           echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
-  #         else
-  #           echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
-  #           cat trigger_response.txt
-  #           exit 1
-  #         fi
+          tags: bahmni/bahmni-web:ipd-${{ github.run_number }},bahmni/bahmni-web:ipd
+  trigger-workflow:
+    name: Trigger workflow to deploy to Docker env
+    needs:
+      - build-publish-docker
+      - Trivy
+    runs-on: ubuntu-latest
+    env:
+      EVENT_TYPE: openmrs-module-bahmniapps-event
+    steps:
+      - name: Create repository_dispatch
+        run: |
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.IPD_PAT }}' https://api.github.com/repos/${{ secrets.IPD_ORG_NAME }}/${{ secrets.IPD_REPOSITORY_NAME }}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
